exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //compilers/llvm:util_test
-----------------------------------------------------------------------------
I0308 09:17:07.456022 4460180928 test.py:79] Running pytest with arguments: ['/private/var/tmp/_bazel_cec/ce66aefd86f9b09aced8556389d9936d/sandbox/darwin-sandbox/240/execroot/phd/bazel-out/darwin-fastbuild/bin/compilers/llvm/util_test.runfiles/phd/compilers/llvm/util_test.py', '-vv', '--maxfail=1', '--durations=1']
fatal: --local can only be used inside a git repository
============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.4.1, py-1.5.2, pluggy-0.6.0 -- /usr/local/opt/python/bin/python3.6
cachedir: .pytest_cache
benchmark: 3.1.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /private/var/tmp/_bazel_cec/ce66aefd86f9b09aced8556389d9936d/sandbox/darwin-sandbox/240/execroot/phd/bazel-out/darwin-fastbuild/bin/compilers/llvm/util_test.runfiles/phd, inifile:
plugins: benchmark-3.1.1, mock-1.10.0, cov-2.5.1
collecting ... collected 5 items

compilers/llvm/util_test.py::test_GetOptArgs_black_box[cflags0] PASSED   [ 20%]
compilers/llvm/util_test.py::test_GetOptArgs_black_box[cflags1] PASSED   [ 40%]
compilers/llvm/util_test.py::test_GetOptArgs_black_box[cflags2] PASSED   [ 60%]
compilers/llvm/util_test.py::test_GetOptArgs_black_box[cflags3] PASSED   [ 80%]
compilers/llvm/util_test.py::test_GetOptArgs_bad_args PASSED             [100%]

=========================== slowest 1 test durations ===========================
0.15s call     compilers/llvm/util_test.py::test_GetOptArgs_bad_args
=========================== 5 passed in 0.32 seconds ===========================
